[task-20] feat: add some gone

diff --git a/.husky/commit-msg b/.husky/commit-msg
--- a/.husky/commit-msg
+++ b/.husky/commit-msg
@@ -1,10 +1,15 @@
-#!/bin/sh
+#!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
 commit_msg_file=$(git rev-parse --git-dir)/COMMIT_EDITMSG
 
+# Define the allowed commit types
+allowed_types='build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test'
+
 # Check if the commit message matches the desired pattern
-if ! grep -qE "^\[task-[a-zA-Z0-9]+\] (build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test): " "$commit_msg_file"; then
-    echo "Aborting commit. Commit message does not match the required pattern. Your commit message should follow the pattern [task-id] type: commit message"
+if ! grep -qE "^\[task-[a-zA-Z0-9]+\] ($allowed_types): " "$commit_msg_file"; then
+    echo "Aborting commit. Commit message does not match the required pattern. Your commit message should follow the pattern [task-id] $allowed_types: your commit message"
+    # echo "Allowed types are: $allowed_types"
     exit 1
 fi
+
